version: '3'

services:
  server:
    image: honeyball/np_server:latest
    ports:
      - 3000:3000
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - overlay
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - overlay

networks:
  overlay:
